# Generated by Django 3.2.4 on 2021-06-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_main', models.URLField()),
                ('img_2', models.URLField(blank=True)),
                ('img_3', models.URLField(blank=True)),
                ('img_4', models.URLField(blank=True)),
                ('img_5', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Jerusalem', 'Jerusalem'), ('Center', 'Center'), ('Eilat', 'Eilat'), ('South', 'South'), ('North', 'North')], default='North', max_length=20)),
                ('beds', models.IntegerField(max_length=2)),
                ('kosher', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('accessible', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
