# Generated by Django 3.2.4 on 2021-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210613_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='beds',
            new_name='bedrooms',
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='sleeps',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
    ]
