# Generated by Django 3.2.4 on 2021-06-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_bathrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='smoking',
        ),
    ]
