# Generated by Django 3.2.4 on 2021-06-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_smoking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='img_5',
        ),
    ]
