# Generated by Django 3.2.4 on 2021-06-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0004_auto_20210614_1243'),
        ('accounts', '0004_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('traded_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('host1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host1', to='accounts.profile')),
                ('host2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host2', to='accounts.profile')),
                ('listing1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing1', to='listings.listing')),
                ('listing2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing2', to='listings.listing')),
            ],
        ),
    ]
