# Generated by Django 3.2.4 on 2021-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
